#!/bin/sh
# Gradle wrapper script - minimal version for CI use
# In normal use, this would be generated by `gradle wrapper`
# For CI/CD we provide a minimal script

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
GRADLE_USER_HOME="${GRADLE_USER_HOME:-$HOME/.gradle}"

# Download gradle if not present
GRADLE_VERSION="6.7.1"
GRADLE_DIR="$GRADLE_USER_HOME/wrapper/dists/gradle-$GRADLE_VERSION-bin"
GRADLE_ZIP="$GRADLE_DIR/gradle-$GRADLE_VERSION-bin.zip"
GRADLE_HOME="$GRADLE_DIR/gradle-$GRADLE_VERSION"

if [ ! -d "$GRADLE_HOME" ]; then
    echo "Downloading Gradle $GRADLE_VERSION..."
    mkdir -p "$GRADLE_DIR"
    if [ ! -f "$GRADLE_ZIP" ]; then
        curl -L -o "$GRADLE_ZIP" "https://mirrors.cloud.tencent.com/gradle/gradle-$GRADLE_VERSION-bin.zip" \
            || curl -L -o "$GRADLE_ZIP" "https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip"
    fi
    echo "Extracting Gradle..."
    cd "$GRADLE_DIR"
    unzip -q "$GRADLE_ZIP"
    cd "$DIR"
fi

# Find gradle executable
GRADLE_BIN=""
for d in "$GRADLE_HOME"/*/; do
    if [ -x "${d}bin/gradle" ]; then
        GRADLE_BIN="${d}bin/gradle"
        break
    fi
done

if [ -z "$GRADLE_BIN" ] && [ -x "$GRADLE_HOME/bin/gradle" ]; then
    GRADLE_BIN="$GRADLE_HOME/bin/gradle"
fi

if [ -z "$GRADLE_BIN" ]; then
    echo "ERROR: Cannot find gradle binary in $GRADLE_HOME"
    ls -la "$GRADLE_HOME"
    exit 1
fi

echo "Using Gradle: $GRADLE_BIN"
exec "$GRADLE_BIN" "$@"
